project:
  type: website
  output-dir: docs
  preview:
    browser: true

lang: kr
date-format: "YYYY년 MM월 DD일"

website:
  title: "duksoo"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: data.qmd
        text: "데이터"
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

