project:
  type: website
  output-dir: docs
  preview:
    browser: true

lang: kr
date-format: "YYYY년 MM월 DD일"

website:
  title: "duksoo"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: "경기도 학교"
        menu:
        - href: school_data.qmd
          text: "경기 초중등"
        - href: closed_school.qmd
          text: "경기 폐교현황"
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

