project:
  type: website
  output-dir: docs
  preview:
    browser: true

lang: kr
date-format: "YYYY년 MM월 DD일"

website:
  title: "duksoo"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: school_data.qmd
        text: "경기 초중등"
      - href: student_data.qmd
        text: "경기 학생수"
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

