---
title: "경기도 폐교현황"
subtitle: "초중등 학생 현황"
author:
  - name: 이광춘
    url: https://www.linkedin.com/in/kwangchunlee/
    affiliation: 한국 R 사용자회
    affiliation-url: https://github.com/bit2r
title-block-banner: true
#title-block-banner: "#562457"
format:
  html:
    css: css/quarto.css
    theme: flatly
    code-fold: true
    toc: true
    toc-depth: 3
    toc-title: 목차
    number-sections: true
    highlight-style: github    
    self-contained: false
filters:
   - lightbox
lightbox: auto
link-citations: yes
knitr:
  opts_chunk: 
    message: false
    warning: false
    collapse: true
    comment: "#>" 
    R.options:
      knitr.graphics.auto_pdf: true
editor_options: 
  chunk_output_type: console
---

# 경기도 초중등 학교

# 데이터

- [학교알리미 - 공개용데이터](https://www.schoolinfo.go.kr/ng/go/pnnggo_a01_l2.do)

# 학교현황



```{r}
#| eval: false
library(tidyverse)
library(httr)

school_url <- glue::glue("https://www.schoolinfo.go.kr/openApi.do",
                         "?apiKey={Sys.getenv('SCHOOL_INFO_KEY')}",
                         "&apiType=0",
                         "&pbanYr=2023",
                         "&schulKndCode=02")

resp <- GET(school_url)

school_json <- content(resp, "text", encoding='utf-8')
school_json
```


```{python}
#| eval: false
import requests
import json

school_url = f"https://www.schoolinfo.go.kr/openApi.do?apiKey={}&apiType=0&pbanYr=2023&schulKndCode=02".format(os.environ.get("SCHOOL_INFO_KEY"))

resp = requests.get(school_url, verify=False)

school_json = json.loads(resp.text)

with open("data/school_info_data.json", "w") as file:
    json.dump(school_json, file)
```

# 데이터 후처리

```{r}
library(jsonlite)
library(tidyverse)

school_info_json <- read_json("data/school_info_data.json")

school_info <- map_df(school_info_json$list, as.data.frame) %>% 
  as_tibble()

school_info %>% 
  filter(str_detect(ATPT_OFCDC_ORG_NM, "경기도교육청")) %>% 
  reactable::reactable()
```


# 신설/폐교 정보

- [신설/폐교 학교정보](https://www.schoolinfo.go.kr/ei/ss/pneiss_a07_s0.do)

## 신설 학교

```{r}
library(tidyverse)
library(readxl)

open_school <- read_excel("data/신설예정학교-경기.xlsx", skip = 2) %>% 
  mutate(개교예정년월 = as.character(개교예정년월))

open_school %>% 
  reactable::reactable()

```


## 폐교 학교

```{r}

close_school <- read_excel("data/폐교정보-경기.xlsx", skip = 2) %>% 
  mutate(폐교연도 = as.character(폐교연도))

close_school %>% 
  reactable::reactable()

```


# 지도

## 지도코딩

```{r}
library(httr)
library(tidyverse)
library(jsonlite)

# HTTP 요청을 실행합니다. 
get_lonlat <- function(address = '서울특별시 강남구 역삼동 737') {
  response <- GET(url = 'https://dapi.kakao.com/v2/local/search/address.json',
                query = list(query = address),
                add_headers(Authorization = paste0("KakaoAK ", Sys.getenv('DAUM_MAP_API_KEY'))))

  # KPMG 지리정보 데이터프레임
  response_list <- response %>% 
    content(as = 'text') %>% 
    fromJSON()
  
  ## 도로명주소
  lonlat_tbl <- response_list$documents$road_address %>% 
    select(address_name, building_name, x,y) %>% 
    slice(1)
  
  return(lonlat_tbl)
}

safely_get_lonlat <- safely(get_lonlat, otherwise = "error")


close_school_geocode <- close_school %>% 
  mutate(data = map(주소, safely_get_lonlat))

close_school_geocode_tbl <- close_school_geocode %>% 
  mutate(result = map(data, "result")) %>% 
  filter(result != "error") %>% 
  unnest(result) %>% 
  select(-data)

```

```{r}
#| column: page
library(leaflet)

close_school_geocode_tbl %>% 
  mutate(x = as.numeric(x),
         y = as.numeric(y)) %>% 
  leaflet(height=800) %>% 
    addProviderTiles(providers$OpenStreetMap) %>% 
    addMarkers(lng=~x, lat=~y, clusterOptions = markerClusterOptions(),
               popup = ~ as.character(paste0("<strong>", paste0("폐교학교명:",`학교명`), "</strong><br>",
                                                 "-----------------------------------------------------------<br>",
                                                 "&middot; 폐교연도: ", `폐교연도`, "<br>",
                                                 "&middot; 급별: ", `급별`, "<br>",
                                                 "&middot; 지역교육청: ", `지역교육청`, "<br>",
                                                 "&middot; 주소: ", `주소`, "<br>"
                   )))
    
```

